	.align 2
voicegroup570::
	voice_directsound 40, 0, DirectSoundWaveData_BWInstrumentSample039, 255, 250, 0, 215 @ 0 | Direct | 
	voice_directsound 48, 0, DirectSoundWaveData_BWInstrumentSample040, 255, 250, 0, 215 @ 1 | Direct | 
	voice_directsound 64, 0, DirectSoundWaveData_BWInstrumentSample041, 255, 250, 0, 215 @ 2 | Direct | 
	voice_directsound 76, 0, DirectSoundWaveData_BWInstrumentSample042, 255, 250, 0, 215 @ 3 | Direct | 
