	.align 2
voicegroup551::
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample285, 255, 245, 0, 165 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample286, 255, 245, 0, 165 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample287, 255, 245, 0, 165 @ 2 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample288, 255, 245, 0, 165 @ 3 | Direct | 
	voice_directsound 84, 0, DirectSoundWaveData_BWInstrumentSample289, 230, 230, 230, 230 @ 4 | Direct | 
