	.align 2
voicegroup538::
	voice_keysplit voicegroup595, KeySplitTableBW46 @ 0 | Multi | 
	voice_keysplit voicegroup555, KeySplitTableBW07 @ 1 | Multi | 
	voice_keysplit voicegroup556, KeySplitTableBW08 @ 2 | Multi | 
	voice_keysplit voicegroup557, KeySplitTableBW09 @ 3 | Multi | 
	voice_keysplit voicegroup558, KeySplitTableBW10 @ 4 | Multi | 
	voice_keysplit voicegroup559, KeySplitTableBW11 @ 5 | Multi | 
	voice_keysplit voicegroup560, KeySplitTableBW12 @ 6 | Multi | 
	voice_keysplit voicegroup561, KeySplitTableBW13 @ 7 | Multi | 
	voice_keysplit voicegroup562, KeySplitTableBW14 @ 8 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample279, 255, 240, 0, 185 @ 9 | Direct | 
	voice_keysplit voicegroup564, KeySplitTableBW16 @ 10 | Multi | 
	voice_keysplit voicegroup565, KeySplitTableBW17 @ 11 | Multi | 
	voice_keysplit voicegroup566, KeySplitTableBW18 @ 12 | Multi | 
	voice_keysplit voicegroup567, KeySplitTableBW19 @ 13 | Multi | 
	voice_keysplit voicegroup553, KeySplitTableBW05 @ 14 | Multi | 
	voice_keysplit voicegroup569, KeySplitTableBW21 @ 15 | Multi | 
	voice_keysplit voicegroup570, KeySplitTableBW22 @ 16 | Multi | 
	voice_keysplit voicegroup571, KeySplitTableBW23 @ 17 | Multi | 
	voice_keysplit voicegroup572, KeySplitTableBW24 @ 18 | Multi | 
	voice_keysplit voicegroup573, KeySplitTableBW25 @ 19 | Multi | 
	voice_keysplit voicegroup574, KeySplitTableBW26 @ 20 | Multi | 
	voice_keysplit voicegroup600, KeySplitTableBW51 @ 21 | Multi | 
	voice_keysplit voicegroup575, KeySplitTableBW27 @ 22 | Multi | 
	voice_keysplit voicegroup576, KeySplitTableBW28 @ 23 | Multi | 
	voice_keysplit voicegroup577, KeySplitTableBW29 @ 24 | Multi | 
	voice_keysplit voicegroup578, KeySplitTableBW30 @ 25 | Multi | 
	voice_keysplit voicegroup579, KeySplitTableBW31 @ 26 | Multi | 
	voice_keysplit voicegroup580, KeySplitTableBW32 @ 27 | Multi | 
	voice_keysplit voicegroup581, KeySplitTableBW33 @ 28 | Multi | 
	voice_keysplit voicegroup582, KeySplitTableBW34 @ 29 | Multi | 
	voice_keysplit voicegroup583, KeySplitTableBW35 @ 30 | Multi | 
	voice_keysplit voicegroup584, KeySplitTableBW36 @ 31 | Multi | 
	voice_keysplit voicegroup596, KeySplitTableBW47 @ 32 | Multi | 
	voice_keysplit voicegroup586, KeySplitTableBW38 @ 33 | Multi | 
	voice_keysplit voicegroup587, KeySplitTableBW39 @ 34 | Multi | 
	voice_keysplit voicegroup588, KeySplitTableBW40 @ 35 | Multi | 
	voice_keysplit voicegroup589, KeySplitTableBW41 @ 36 | Multi | 
	voice_keysplit voicegroup590, KeySplitTableBW42 @ 37 | Multi | 
	voice_keysplit voicegroup591, KeySplitTableBW43 @ 38 | Multi | 
	voice_keysplit_all voicegroup543 @ 39 | Drum | 
	voice_keysplit_all voicegroup544 @ 40 | Drum | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample145, 255, 245, 130, 165 @ 41 | Direct | 
	voice_keysplit voicegroup592, KeySplitTableBW44 @ 42 | Multi | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 43 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample149, 255, 240, 110, 165 @ 44 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample150, 130, 45, 210, 240 @ 45 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample151, 255, 245, 110, 165 @ 46 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample152, 60, 240, 0, 80 @ 47 | Direct | 
	voice_keysplit voicegroup576, KeySplitTableBW28 @ 48 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample195, 255, 245, 0, 165 @ 49 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample208, 145, 0, 145, 165 @ 50 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample209, 255, 245, 0, 165 @ 51 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample208, 145, 0, 145, 165 @ 52 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample210, 255, 245, 0, 165 @ 53 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample181, 255, 0, 255, 165 @ 54 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample153, 255, 245, 90, 185 @ 55 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample154, 255, 245, 90, 165 @ 56 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample155, 255, 245, 90, 165 @ 57 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 58 | Square-1 | --
	voice_keysplit voicegroup578, KeySplitTableBW29 @ 59 | Multi | 
	voice_keysplit_all voicegroup546 @ 60 | Drum | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample157, 255, 245, 210, 210 @ 61 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample158, 255, 250, 190, 185 @ 62 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample159, 255, 245, 200, 165 @ 63 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample160, 255, 250, 230, 225 @ 64 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample161, 255, 240, 130, 165 @ 65 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample159, 255, 250, 0, 165 @ 66 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample162, 255, 250, 235, 185 @ 67 | Direct | 
	voice_keysplit voicegroup598, KeySplitTableBW49 @ 68 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample269, 185, 0, 185, 185 @ 69 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample212, 255, 0, 255, 165 @ 70 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample314, 255, 0, 255, 165 @ 71 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample211, 255, 245, 0, 165 @ 72 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample272, 255, 245, 0, 208 @ 73 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample273, 55, 0, 165, 165 @ 74 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample193, 255, 0, 255, 205 @ 75 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample190, 255, 245, 0, 165 @ 76 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample391, 255, 240, 110, 225 @ 77 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample177, 255, 0, 255, 165 @ 78 | Direct | 
	voice_keysplit voicegroup575, KeySplitTableBW27 @ 79 | Multi | 
	voice_keysplit voicegroup575, KeySplitTableBW27 @ 80 | Multi | 
	voice_keysplit voicegroup596, KeySplitTableBW60 @ 81 | Multi | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 82 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample282, 75, 0, 175, 255 @ 83 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample219, 255, 245, 0, 165 @ 84 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample254, 255, 0, 255, 165 @ 85 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample199, 255, 0, 255, 165 @ 86 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample197, 155, 0, 155, 165 @ 87 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample198, 145, 0, 145, 165 @ 88 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample185, 255, 0, 255, 165 @ 89 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample183, 255, 0, 255, 165 @ 90 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample187, 255, 0, 255, 165 @ 91 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample188, 255, 0, 255, 165 @ 92 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample189, 165, 0, 165, 165 @ 93 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample205, 165, 0, 165, 165 @ 94 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample206, 165, 0, 165, 165 @ 95 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample207, 255, 250, 0, 165 @ 96 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample170, 255, 0, 255, 235 @ 97 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample171, 255, 245, 0, 224 @ 98 | Direct | 
	voice_keysplit voicegroup554, KeySplitTableBW06 @ 99 | Multi | 
	voice_keysplit voicegroup594, KeySplitTableBW45 @ 100 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample191, 255, 0, 255, 165 @ 101 | Direct | 
	voice_keysplit voicegroup597, KeySplitTableBW48 @ 102 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample194, 255, 0, 255, 165 @ 103 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample166, 15, 0, 165, 165 @ 104 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample255, 255, 0, 160, 205 @ 105 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample256, 200, 0, 200, 165 @ 106 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample257, 200, 0, 200, 165 @ 107 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample258, 255, 245, 0, 165 @ 108 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample182, 255, 0, 255, 165 @ 109 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample172, 255, 0, 255, 165 @ 110 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample173, 255, 250, 0, 224 @ 111 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample174, 255, 0, 255, 165 @ 112 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample175, 255, 0, 255, 165 @ 113 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample176, 255, 0, 255, 165 @ 114 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample178, 255, 0, 255, 165 @ 115 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample179, 255, 0, 255, 165 @ 116 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample180, 255, 0, 255, 165 @ 117 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample196, 224, 245, 0, 200 @ 118 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample201, 255, 0, 255, 165 @ 119 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample202, 255, 0, 255, 165 @ 120 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample203, 255, 0, 255, 165 @ 121 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample204, 165, 165, 0, 165 @ 122 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 123 | Square-1 | --
	voice_keysplit voicegroup600, KeySplitTableBW51 @ 124 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample166, 255, 0, 225, 165 @ 125 | Direct | 
	voice_keysplit voicegroup599, KeySplitTableBW50 @ 126 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample200, 255, 0, 255, 165 @ 127 | Direct | 
