	.align 2
voicegroup600::
	voice_directsound 36, 0, DirectSoundWaveData_BWInstrumentSample303, 165, 0, 165, 165 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample315, 200, 0, 200, 165 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample276, 255, 245, 0, 210 @ 2 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample277, 255, 245, 0, 210 @ 3 | Direct | 
	voice_directsound 84, 0, DirectSoundWaveData_BWInstrumentSample001, 255, 240, 0, 215 @ 4 | Direct | 
