	.align 2
voicegroup595::
	voice_directsound 36, 0, DirectSoundWaveData_BWInstrumentSample274, 255, 245, 0, 210 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample275, 255, 245, 0, 210 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample276, 255, 245, 0, 210 @ 2 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample277, 255, 245, 0, 210 @ 3 | Direct | 
	voice_directsound 84, 0, DirectSoundWaveData_BWInstrumentSample001, 255, 245, 0, 210 @ 4 | Direct | 
