	.align 2
voicegroup537::
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample220, 255, 0, 255, 165 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample221, 255, 0, 255, 165 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample222, 255, 0, 255, 165 @ 2 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample223, 255, 0, 255, 165 @ 3 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample224, 255, 0, 255, 165 @ 4 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample225, 255, 0, 255, 165 @ 5 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample226, 255, 0, 255, 165 @ 6 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample227, 255, 0, 255, 165 @ 7 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample228, 255, 0, 255, 165 @ 8 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample229, 255, 0, 255, 165 @ 9 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample230, 55, 0, 255, 165 @ 10 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample231, 255, 0, 255, 165 @ 11 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample232, 255, 0, 255, 165 @ 12 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample233, 255, 0, 255, 165 @ 13 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample234, 255, 0, 255, 165 @ 14 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample235, 255, 0, 255, 165 @ 15 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample236, 255, 0, 255, 165 @ 16 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample237, 255, 0, 255, 165 @ 17 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample238, 255, 0, 255, 165 @ 18 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample239, 255, 0, 255, 165 @ 19 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample240, 255, 0, 255, 165 @ 20 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample241, 255, 0, 255, 165 @ 21 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample242, 255, 0, 255, 165 @ 22 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample243, 255, 0, 255, 165 @ 23 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample244, 255, 0, 255, 165 @ 24 | Direct | 
	voice_keysplit voicegroup578, KeySplitTableBW30 @ 25 | Multi | 
	voice_keysplit voicegroup579, KeySplitTableBW31 @ 26 | Multi | 
	voice_keysplit voicegroup580, KeySplitTableBW32 @ 27 | Multi | 
	voice_keysplit voicegroup581, KeySplitTableBW33 @ 28 | Multi | 
	voice_keysplit voicegroup582, KeySplitTableBW34 @ 29 | Multi | 
	voice_keysplit voicegroup583, KeySplitTableBW35 @ 30 | Multi | 
	voice_keysplit voicegroup584, KeySplitTableBW36 @ 31 | Multi | 
	voice_keysplit voicegroup585, KeySplitTableBW37 @ 32 | Multi | 
	voice_keysplit voicegroup586, KeySplitTableBW38 @ 33 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample184, 250, 250, 250, 190 @ 34 | Direct | 
	voice_keysplit voicegroup588, KeySplitTableBW40 @ 35 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample213, 255, 245, 0, 165 @ 36 | Direct | 
	voice_keysplit voicegroup568, KeySplitTableBW20 @ 37 | Multi | 
	voice_keysplit voicegroup591, KeySplitTableBW43 @ 38 | Multi | 
	voice_keysplit_all voicegroup543 @ 39 | Drum | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample186, 170, 160, 180, 210 @ 40 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample186, 170, 160, 180, 210 @ 41 | Direct | 
	voice_directsound 62, 0, DirectSoundWaveData_BWInstrumentSample250, 255, 0, 255, 165 @ 42 | Direct | 
	voice_directsound 63, 0, DirectSoundWaveData_BWInstrumentSample250, 255, 0, 255, 165 @ 43 | Direct | 
	voice_directsound 64, 0, DirectSoundWaveData_BWInstrumentSample250, 255, 0, 255, 165 @ 44 | Direct | 
	voice_directsound 65, 0, DirectSoundWaveData_BWInstrumentSample250, 255, 0, 255, 165 @ 45 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample251, 255, 0, 255, 165 @ 46 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample252, 255, 0, 255, 165 @ 47 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample252, 255, 0, 255, 165 @ 48 | Direct | 
	voice_directsound 62, 0, DirectSoundWaveData_BWInstrumentSample252, 255, 0, 255, 165 @ 49 | Direct | 
	voice_directsound 63, 0, DirectSoundWaveData_BWInstrumentSample252, 255, 0, 255, 165 @ 50 | Direct | 
	voice_directsound 64, 0, DirectSoundWaveData_BWInstrumentSample252, 255, 0, 255, 165 @ 51 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample253, 255, 0, 255, 165 @ 52 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample253, 255, 0, 255, 165 @ 53 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample253, 255, 0, 255, 165 @ 54 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample253, 255, 0, 255, 165 @ 55 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample154, 255, 245, 90, 165 @ 56 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample155, 255, 245, 90, 165 @ 57 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 58 | Square-1 | --
	voice_keysplit voicegroup578, KeySplitTableBW29 @ 59 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample168, 255, 205, 220, 243 @ 60 | Direct | 
	voice_keysplit voicegroup594, KeySplitTableBW45 @ 61 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample160, 255, 250, 230, 165 @ 62 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample157, 255, 245, 210, 165 @ 63 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample169, 170, 160, 180, 210 @ 64 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample167, 255, 188, 220, 243 @ 65 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 66 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 67 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 68 | Square-1 | --
	voice_keysplit voicegroup564, KeySplitTableBW16 @ 69 | Multi | 
	voice_keysplit voicegroup567, KeySplitTableBW19 @ 70 | Multi | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 71 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 72 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 73 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 74 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 75 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 76 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 77 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 78 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 79 | Square-1 | --
	voice_keysplit_all voicegroup545 @ 80 | Drum | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 81 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 82 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 83 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 84 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 85 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 86 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 87 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 88 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 89 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 90 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 91 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 92 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 93 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 94 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 95 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 96 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 97 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 98 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 99 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 100 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 101 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 102 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 103 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 104 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 105 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 106 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 107 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 108 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 109 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 110 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 111 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 112 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 113 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 114 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 115 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 116 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 117 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 118 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 119 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 120 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 121 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 122 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 123 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 124 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 125 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 126 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 127 | Square-1 | --
