	.align 2
voicegroup556::
	voice_directsound 36, 0, DirectSoundWaveData_BWInstrumentSample004, 255, 250, 5, 180 @ 0 | Direct | 
	voice_directsound 48, 0, DirectSoundWaveData_BWInstrumentSample005, 255, 250, 5, 180 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample006, 255, 250, 5, 180 @ 2 | Direct | 
	voice_directsound 72, 0, DirectSoundWaveData_BWInstrumentSample007, 255, 250, 5, 180 @ 3 | Direct | 
