	.align 2
voicegroup576::
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample359, 255, 250, 175, 210 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample360, 255, 250, 175, 210 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample058, 255, 250, 175, 210 @ 2 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample059, 255, 250, 175, 210 @ 3 | Direct | 
