	.align 2
voicegroup572::
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample047, 255, 240, 5, 165 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample048, 255, 240, 5, 165 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample049, 255, 240, 5, 165 @ 2 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample050, 255, 240, 5, 165 @ 3 | Direct | 
