	.align 2
voicegroup579::
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample066, 255, 235, 0, 165 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample067, 255, 235, 0, 165 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample068, 255, 235, 0, 165 @ 2 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample069, 255, 235, 0, 165 @ 3 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample070, 255, 235, 0, 165 @ 4 | Direct | 
