	.align 2
voicegroup548::
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample420, 255, 0, 255, 165 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample421, 255, 0, 255, 165 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample422, 255, 235, 0, 165 @ 2 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample423, 255, 0, 255, 165 @ 3 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample424, 255, 245, 0, 165 @ 4 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample455, 255, 0, 255, 165 @ 5 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample456, 255, 0, 255, 165 @ 6 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample457, 255, 0, 255, 165 @ 7 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample458, 255, 0, 255, 165 @ 8 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample459, 255, 0, 255, 165 @ 9 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample459, 255, 0, 255, 165 @ 10 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample437, 255, 0, 255, 165 @ 11 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample438, 255, 0, 255, 165 @ 12 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample439, 255, 245, 0, 165 @ 13 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample440, 255, 0, 255, 165 @ 14 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample264, 255, 0, 255, 165 @ 15 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample265, 255, 0, 255, 165 @ 16 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample265, 255, 0, 255, 165 @ 17 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample266, 255, 0, 255, 165 @ 18 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample267, 255, 0, 255, 165 @ 19 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample278, 255, 245, 0, 165 @ 20 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample278, 255, 245, 0, 165 @ 21 | Direct | 
	voice_directsound 42, 0, DirectSoundWaveData_BWInstrumentSample118, 255, 150, 0, 165 @ 22 | Direct | 
	voice_directsound 57, 0, DirectSoundWaveData_BWInstrumentSample294, 255, 245, 0, 165 @ 23 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample467, 255, 0, 255, 165 @ 24 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample468, 255, 0, 255, 165 @ 25 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample469, 255, 0, 255, 165 @ 26 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample470, 255, 0, 255, 165 @ 27 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample471, 255, 0, 255, 165 @ 28 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample472, 255, 0, 255, 165 @ 29 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample473, 255, 0, 255, 165 @ 30 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample474, 255, 0, 255, 165 @ 31 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample475, 255, 0, 255, 165 @ 32 | Direct | 
	voice_directsound 33, 0, DirectSoundWaveData_BWInstrumentSample110, 255, 245, 0, 165 @ 33 | Direct | 
	voice_directsound 34, 0, DirectSoundWaveData_BWInstrumentSample111, 255, 245, 0, 165 @ 34 | Direct | 
	voice_directsound 35, 0, DirectSoundWaveData_BWInstrumentSample112, 255, 245, 0, 165 @ 35 | Direct | 
	voice_directsound 36, 0, DirectSoundWaveData_BWInstrumentSample113, 255, 230, 0, 165 @ 36 | Direct | 
	voice_directsound 37, 0, DirectSoundWaveData_BWInstrumentSample114, 255, 245, 0, 165 @ 37 | Direct | 
	voice_directsound 38, 0, DirectSoundWaveData_BWInstrumentSample115, 255, 245, 0, 165 @ 38 | Direct | 
	voice_directsound 39, 0, DirectSoundWaveData_BWInstrumentSample116, 255, 245, 0, 165 @ 39 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample394, 255, 245, 0, 165 @ 40 | Direct | 
	voice_directsound 41, 0, DirectSoundWaveData_BWInstrumentSample117, 255, 245, 0, 165 @ 41 | Direct | 
	voice_directsound 42, 0, DirectSoundWaveData_BWInstrumentSample118, 255, 245, 0, 165 @ 42 | Direct | 
	voice_directsound 43, 0, DirectSoundWaveData_BWInstrumentSample119, 255, 245, 0, 165 @ 43 | Direct | 
	voice_directsound 44, 0, DirectSoundWaveData_BWInstrumentSample119, 255, 245, 0, 165 @ 44 | Direct | 
	voice_directsound 45, 0, DirectSoundWaveData_BWInstrumentSample120, 255, 245, 0, 165 @ 45 | Direct | 
	voice_directsound 46, 0, DirectSoundWaveData_BWInstrumentSample121, 255, 245, 0, 165 @ 46 | Direct | 
	voice_directsound 47, 0, DirectSoundWaveData_BWInstrumentSample122, 255, 245, 0, 165 @ 47 | Direct | 
	voice_directsound 48, 0, DirectSoundWaveData_BWInstrumentSample123, 255, 245, 0, 165 @ 48 | Direct | 
	voice_directsound 49, 0, DirectSoundWaveData_BWInstrumentSample124, 255, 245, 0, 165 @ 49 | Direct | 
	voice_directsound 50, 0, DirectSoundWaveData_BWInstrumentSample124, 255, 245, 0, 165 @ 50 | Direct | 
	voice_directsound 51, 0, DirectSoundWaveData_BWInstrumentSample124, 255, 245, 0, 165 @ 51 | Direct | 
	voice_directsound 52, 0, DirectSoundWaveData_BWInstrumentSample125, 255, 245, 0, 165 @ 52 | Direct | 
	voice_directsound 53, 0, DirectSoundWaveData_BWInstrumentSample126, 255, 245, 0, 165 @ 53 | Direct | 
	voice_directsound 54, 0, DirectSoundWaveData_BWInstrumentSample127, 255, 245, 0, 165 @ 54 | Direct | 
	voice_directsound 55, 0, DirectSoundWaveData_BWInstrumentSample128, 255, 245, 0, 165 @ 55 | Direct | 
	voice_directsound 56, 0, DirectSoundWaveData_BWInstrumentSample129, 255, 245, 0, 165 @ 56 | Direct | 
	voice_directsound 57, 0, DirectSoundWaveData_BWInstrumentSample130, 255, 245, 0, 165 @ 57 | Direct | 
	voice_directsound 58, 0, DirectSoundWaveData_BWInstrumentSample130, 255, 245, 0, 165 @ 58 | Direct | 
	voice_directsound 59, 0, DirectSoundWaveData_BWInstrumentSample131, 255, 245, 0, 165 @ 59 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample132, 255, 245, 0, 165 @ 60 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample133, 255, 245, 0, 165 @ 61 | Direct | 
	voice_directsound 62, 0, DirectSoundWaveData_BWInstrumentSample134, 255, 245, 0, 165 @ 62 | Direct | 
	voice_directsound 63, 0, DirectSoundWaveData_BWInstrumentSample135, 255, 245, 0, 165 @ 63 | Direct | 
	voice_directsound 64, 0, DirectSoundWaveData_BWInstrumentSample136, 255, 245, 0, 165 @ 64 | Direct | 
	voice_directsound 65, 0, DirectSoundWaveData_BWInstrumentSample136, 255, 245, 0, 165 @ 65 | Direct | 
	voice_directsound 66, 0, DirectSoundWaveData_BWInstrumentSample136, 255, 245, 0, 165 @ 66 | Direct | 
	voice_directsound 67, 0, DirectSoundWaveData_BWInstrumentSample137, 255, 245, 0, 165 @ 67 | Direct | 
	voice_directsound 68, 0, DirectSoundWaveData_BWInstrumentSample138, 255, 245, 0, 165 @ 68 | Direct | 
	voice_directsound 69, 0, DirectSoundWaveData_BWInstrumentSample139, 255, 245, 0, 165 @ 69 | Direct | 
	voice_directsound 70, 0, DirectSoundWaveData_BWInstrumentSample136, 255, 245, 0, 165 @ 70 | Direct | 
	voice_directsound 71, 0, DirectSoundWaveData_BWInstrumentSample136, 255, 245, 0, 165 @ 71 | Direct | 
	voice_directsound 72, 0, DirectSoundWaveData_BWInstrumentSample136, 255, 245, 0, 165 @ 72 | Direct | 
	voice_directsound 73, 0, DirectSoundWaveData_BWInstrumentSample136, 255, 245, 0, 165 @ 73 | Direct | 
	voice_directsound 74, 0, DirectSoundWaveData_BWInstrumentSample136, 255, 245, 0, 165 @ 74 | Direct | 
	voice_directsound 75, 0, DirectSoundWaveData_BWInstrumentSample136, 255, 245, 0, 165 @ 75 | Direct | 
	voice_directsound 76, 0, DirectSoundWaveData_BWInstrumentSample136, 255, 245, 0, 165 @ 76 | Direct | 
	voice_directsound 77, 0, DirectSoundWaveData_BWInstrumentSample136, 255, 245, 0, 165 @ 77 | Direct | 
	voice_directsound 78, 0, DirectSoundWaveData_BWInstrumentSample140, 255, 245, 0, 165 @ 78 | Direct | 
	voice_directsound 79, 0, DirectSoundWaveData_BWInstrumentSample140, 255, 245, 0, 165 @ 79 | Direct | 
	voice_directsound 80, 0, DirectSoundWaveData_BWInstrumentSample141, 255, 245, 0, 165 @ 80 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample271, 255, 245, 0, 165 @ 81 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample346, 255, 245, 0, 165 @ 82 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample347, 255, 245, 0, 165 @ 83 | Direct | 
	voice_directsound 69, 0, DirectSoundWaveData_BWInstrumentSample346, 255, 245, 0, 165 @ 84 | Direct | 
	voice_directsound 69, 0, DirectSoundWaveData_BWInstrumentSample347, 255, 245, 0, 165 @ 85 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 86 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 87 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 88 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 89 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 90 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 91 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 92 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 93 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 94 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 95 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 96 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 97 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 98 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 99 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 100 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 101 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 102 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 103 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 104 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 105 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 106 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 107 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 108 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 109 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 110 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 111 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 112 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 113 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 114 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 115 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 116 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 117 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 118 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 119 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 120 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 121 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 122 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 123 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 124 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 125 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 126 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 127 | Square-1 | --
