	.align 2
voicegroup547::
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample290, 255, 245, 0, 165 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample215, 255, 0, 255, 165 @ 1 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample215, 255, 0, 255, 165 @ 2 | Direct | 
	voice_directsound 62, 0, DirectSoundWaveData_BWInstrumentSample215, 255, 0, 255, 165 @ 3 | Direct | 
	voice_directsound 63, 0, DirectSoundWaveData_BWInstrumentSample215, 255, 0, 255, 165 @ 4 | Direct | 
	voice_directsound 64, 0, DirectSoundWaveData_BWInstrumentSample215, 255, 0, 255, 165 @ 5 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 6 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 7 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 8 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 9 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 10 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 11 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample327, 255, 0, 255, 165 @ 12 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample328, 255, 0, 255, 165 @ 13 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample329, 255, 0, 255, 165 @ 14 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample330, 255, 0, 255, 165 @ 15 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample331, 255, 0, 255, 165 @ 16 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample332, 255, 0, 255, 165 @ 17 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample333, 255, 0, 255, 165 @ 18 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample334, 255, 0, 255, 165 @ 19 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample335, 255, 0, 255, 165 @ 20 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample336, 255, 0, 255, 165 @ 21 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample336, 255, 0, 255, 165 @ 22 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 23 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 24 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 25 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 26 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 27 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 28 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 29 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 30 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 31 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 32 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 33 | Square-1 | --
	voice_directsound 35, 0, DirectSoundWaveData_BWInstrumentSample112, 255, 245, 0, 165 @ 34 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample394, 255, 245, 0, 165 @ 35 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample270, 255, 245, 255, 165 @ 36 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample270, 255, 245, 255, 165 @ 37 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample324, 255, 245, 0, 165 @ 38 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample324, 255, 245, 0, 165 @ 39 | Direct | 
	voice_directsound 62, 0, DirectSoundWaveData_BWInstrumentSample324, 255, 245, 0, 165 @ 40 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 41 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample325, 255, 245, 0, 165 @ 42 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample325, 255, 245, 0, 165 @ 43 | Direct | 
	voice_directsound 62, 0, DirectSoundWaveData_BWInstrumentSample325, 255, 245, 0, 165 @ 44 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 45 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample326, 255, 245, 0, 165 @ 46 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample326, 255, 245, 0, 165 @ 47 | Direct | 
	voice_directsound 48, 0, DirectSoundWaveData_BWInstrumentSample123, 255, 245, 0, 165 @ 48 | Direct | 
	voice_directsound 49, 0, DirectSoundWaveData_BWInstrumentSample123, 255, 245, 0, 165 @ 49 | Direct | 
	voice_directsound 50, 0, DirectSoundWaveData_BWInstrumentSample123, 255, 245, 0, 165 @ 50 | Direct | 
	voice_directsound 51, 0, DirectSoundWaveData_BWInstrumentSample123, 255, 245, 0, 165 @ 51 | Direct | 
	voice_directsound 52, 0, DirectSoundWaveData_BWInstrumentSample125, 255, 245, 0, 165 @ 52 | Direct | 
	voice_directsound 53, 0, DirectSoundWaveData_BWInstrumentSample123, 255, 245, 0, 165 @ 53 | Direct | 
	voice_directsound 54, 0, DirectSoundWaveData_BWInstrumentSample123, 255, 245, 0, 165 @ 54 | Direct | 
	voice_directsound 55, 0, DirectSoundWaveData_BWInstrumentSample123, 255, 245, 0, 165 @ 55 | Direct | 
	voice_directsound 56, 0, DirectSoundWaveData_BWInstrumentSample123, 255, 245, 0, 165 @ 56 | Direct | 
	voice_directsound 57, 0, DirectSoundWaveData_BWInstrumentSample130, 255, 245, 0, 165 @ 57 | Direct | 
	voice_directsound 58, 0, DirectSoundWaveData_BWInstrumentSample130, 255, 245, 0, 165 @ 58 | Direct | 
	voice_directsound 59, 0, DirectSoundWaveData_BWInstrumentSample130, 255, 245, 0, 165 @ 59 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample130, 255, 245, 0, 165 @ 60 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 61 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 62 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 63 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 64 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 65 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 66 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 67 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 68 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 69 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 70 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 71 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 72 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 73 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 74 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 75 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 76 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 77 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 78 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 79 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 80 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 81 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 82 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 83 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 84 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 85 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 86 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 87 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 88 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 89 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 90 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 91 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 92 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 93 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 94 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 95 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 96 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 97 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 98 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 99 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 100 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 101 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 102 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 103 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 104 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 105 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 106 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 107 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 108 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 109 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 110 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 111 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 112 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 113 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 114 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 115 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 116 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 117 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 118 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 119 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 120 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 121 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 122 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 123 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 124 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 125 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 126 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 127 | Square-1 | --
