	.align 2
voicegroup588::
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample093, 255, 240, 110, 225 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample094, 255, 240, 110, 225 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample095, 255, 240, 110, 225 @ 2 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample096, 255, 240, 110, 225 @ 3 | Direct | 
