	.align 2
voicegroup534::
	voice_keysplit voicegroup550, KeySplitTableBW02 @ 0 | Multi | 
	voice_keysplit voicegroup555, KeySplitTableBW07 @ 1 | Multi | 
	voice_keysplit voicegroup556, KeySplitTableBW08 @ 2 | Multi | 
	voice_keysplit voicegroup557, KeySplitTableBW09 @ 3 | Multi | 
	voice_keysplit voicegroup558, KeySplitTableBW10 @ 4 | Multi | 
	voice_keysplit voicegroup559, KeySplitTableBW11 @ 5 | Multi | 
	voice_keysplit voicegroup560, KeySplitTableBW12 @ 6 | Multi | 
	voice_keysplit voicegroup561, KeySplitTableBW13 @ 7 | Multi | 
	voice_keysplit voicegroup562, KeySplitTableBW14 @ 8 | Multi | 
	voice_keysplit voicegroup563, KeySplitTableBW15 @ 9 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample316, 255, 246, 0, 165 @ 10 | Direct | 
	voice_keysplit voicegroup565, KeySplitTableBW17 @ 11 | Multi | 
	voice_keysplit voicegroup601, KeySplitTableBW52 @ 12 | Multi | 
	voice_keysplit voicegroup567, KeySplitTableBW19 @ 13 | Multi | 
	voice_keysplit voicegroup568, KeySplitTableBW20 @ 14 | Multi | 
	voice_keysplit voicegroup569, KeySplitTableBW21 @ 15 | Multi | 
	voice_keysplit voicegroup570, KeySplitTableBW22 @ 16 | Multi | 
	voice_keysplit voicegroup571, KeySplitTableBW23 @ 17 | Multi | 
	voice_keysplit voicegroup572, KeySplitTableBW24 @ 18 | Multi | 
	voice_keysplit voicegroup573, KeySplitTableBW25 @ 19 | Multi | 
	voice_keysplit voicegroup574, KeySplitTableBW26 @ 20 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample055, 255, 245, 0, 165 @ 21 | Direct | 
	voice_keysplit voicegroup575, KeySplitTableBW27 @ 22 | Multi | 
	voice_keysplit voicegroup576, KeySplitTableBW28 @ 23 | Multi | 
	voice_keysplit voicegroup577, KeySplitTableBW29 @ 24 | Multi | 
	voice_keysplit voicegroup593, KeySplitTableBW30 @ 25 | Multi | 
	voice_keysplit voicegroup579, KeySplitTableBW31 @ 26 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample072, 220, 240, 0, 200 @ 27 | Direct | 
	voice_keysplit voicegroup581, KeySplitTableBW33 @ 28 | Multi | 
	voice_keysplit voicegroup582, KeySplitTableBW34 @ 29 | Multi | 
	voice_keysplit voicegroup583, KeySplitTableBW35 @ 30 | Multi | 
	voice_keysplit voicegroup584, KeySplitTableBW36 @ 31 | Multi | 
	voice_keysplit voicegroup585, KeySplitTableBW37 @ 32 | Multi | 
	voice_keysplit voicegroup586, KeySplitTableBW38 @ 33 | Multi | 
	voice_keysplit voicegroup587, KeySplitTableBW39 @ 34 | Multi | 
	voice_keysplit voicegroup588, KeySplitTableBW40 @ 35 | Multi | 
	voice_keysplit voicegroup589, KeySplitTableBW41 @ 36 | Multi | 
	voice_keysplit voicegroup590, KeySplitTableBW42 @ 37 | Multi | 
	voice_keysplit voicegroup591, KeySplitTableBW43 @ 38 | Multi | 
	voice_keysplit_all voicegroup543 @ 39 | Drum | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample368, 255, 0, 255, 165 @ 40 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample369, 255, 0, 255, 165 @ 41 | Direct | 
	voice_keysplit voicegroup592, KeySplitTableBW44 @ 42 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample305, 165, 250, 0, 165 @ 43 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample149, 255, 240, 110, 165 @ 44 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample150, 130, 45, 210, 240 @ 45 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample151, 255, 245, 110, 165 @ 46 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample152, 60, 240, 0, 80 @ 47 | Direct | 
	voice_square_2_alt 60, 0, 3, 0, 5, 4, 2 @ 48 | Square-2 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 49 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 50 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample181, 255, 0, 255, 165 @ 51 | Direct | 
	voice_square_1_alt 60, 0, 0, 2, 0, 5, 4, 1 @ 52 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 53 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 54 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample153, 255, 245, 90, 185 @ 55 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample154, 255, 245, 90, 165 @ 56 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample155, 255, 245, 90, 165 @ 57 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 58 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample320, 255, 250, 0, 165 @ 59 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 60 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample157, 255, 245, 210, 210 @ 61 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 62 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 63 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample167, 255, 188, 220, 243 @ 64 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 65 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 66 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 67 | Square-1 | --
	voice_keysplit voicegroup598, KeySplitTableBW49 @ 68 | Multi | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 69 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 70 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 71 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 72 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 73 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 74 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample374, 255, 245, 0, 165 @ 75 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 76 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 77 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 78 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 79 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 80 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 81 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 82 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 83 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 84 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 85 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 86 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 87 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 88 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 89 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample340, 255, 0, 255, 165 @ 90 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample341, 255, 0, 255, 165 @ 91 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample342, 255, 0, 255, 165 @ 92 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample343, 255, 0, 255, 165 @ 93 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample338, 255, 245, 0, 165 @ 94 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample157, 255, 245, 210, 210 @ 95 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample337, 240, 200, 245, 220 @ 96 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 97 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample367, 255, 0, 255, 165 @ 98 | Direct | 
	voice_keysplit voicegroup604, KeySplitTableBW57 @ 99 | Multi | 
	voice_keysplit voicegroup594, KeySplitTableBW45 @ 100 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample319, 255, 245, 0, 165 @ 101 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample317, 185, 0, 185, 165 @ 102 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 103 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample353, 255, 0, 255, 165 @ 104 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample357, 255, 245, 0, 165 @ 105 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample356, 255, 0, 255, 165 @ 106 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample355, 255, 0, 255, 165 @ 107 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample354, 255, 0, 255, 165 @ 108 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 109 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample318, 255, 0, 255, 165 @ 110 | Direct | 
	voice_keysplit_all voicegroup547 @ 111 | Drum | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 112 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 113 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 114 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 115 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 116 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 117 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 118 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 119 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 120 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 121 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample303, 165, 0, 165, 165 @ 122 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 123 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample373, 255, 0, 255, 165 @ 124 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 125 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 126 | Square-1 | --
	voice_keysplit voicegroup582, KeySplitTableBW34 @ 127 | Multi | 
