	.align 2
voicegroup571::
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample043, 255, 251, 0, 215 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample044, 255, 251, 0, 215 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample045, 255, 251, 0, 215 @ 2 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample046, 255, 251, 0, 215 @ 3 | Direct | 
