	.align 2
voicegroup590::
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample100, 255, 235, 0, 165 @ 0 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample101, 255, 235, 0, 165 @ 1 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample102, 255, 235, 0, 165 @ 2 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample103, 255, 235, 0, 165 @ 3 | Direct | 
