	.align 2
voicegroup568::
	voice_directsound 43, 0, DirectSoundWaveData_BWInstrumentSample031, 255, 245, 0, 165 @ 0 | Direct | 
	voice_directsound 55, 0, DirectSoundWaveData_BWInstrumentSample032, 255, 245, 0, 165 @ 1 | Direct | 
	voice_directsound 64, 0, DirectSoundWaveData_BWInstrumentSample033, 255, 245, 0, 165 @ 2 | Direct | 
	voice_directsound 72, 0, DirectSoundWaveData_BWInstrumentSample034, 255, 245, 0, 165 @ 3 | Direct | 
