	.align 2
voicegroup569::
	voice_directsound 43, 0, DirectSoundWaveData_BWInstrumentSample035, 255, 245, 0, 200 @ 0 | Direct | 
	voice_directsound 55, 0, DirectSoundWaveData_BWInstrumentSample036, 255, 245, 0, 200 @ 1 | Direct | 
	voice_directsound 64, 0, DirectSoundWaveData_BWInstrumentSample037, 255, 245, 0, 200 @ 2 | Direct | 
	voice_directsound 72, 0, DirectSoundWaveData_BWInstrumentSample038, 255, 245, 0, 200 @ 3 | Direct | 
