	.align 2
voicegroup545::
	voice_keysplit voicegroup549, KeySplitTableBW01 @ 0 | Multi | 
	voice_keysplit voicegroup555, KeySplitTableBW07 @ 1 | Multi | 
	voice_keysplit voicegroup556, KeySplitTableBW08 @ 2 | Multi | 
	voice_keysplit voicegroup557, KeySplitTableBW09 @ 3 | Multi | 
	voice_keysplit voicegroup558, KeySplitTableBW10 @ 4 | Multi | 
	voice_keysplit voicegroup559, KeySplitTableBW11 @ 5 | Multi | 
	voice_keysplit voicegroup560, KeySplitTableBW12 @ 6 | Multi | 
	voice_keysplit voicegroup561, KeySplitTableBW13 @ 7 | Multi | 
	voice_keysplit voicegroup562, KeySplitTableBW14 @ 8 | Multi | 
	voice_keysplit voicegroup563, KeySplitTableBW15 @ 9 | Multi | 
	voice_keysplit voicegroup564, KeySplitTableBW16 @ 10 | Multi | 
	voice_keysplit voicegroup565, KeySplitTableBW17 @ 11 | Multi | 
	voice_keysplit voicegroup566, KeySplitTableBW18 @ 12 | Multi | 
	voice_keysplit voicegroup567, KeySplitTableBW19 @ 13 | Multi | 
	voice_keysplit voicegroup568, KeySplitTableBW20 @ 14 | Multi | 
	voice_keysplit voicegroup569, KeySplitTableBW21 @ 15 | Multi | 
	voice_keysplit voicegroup570, KeySplitTableBW22 @ 16 | Multi | 
	voice_keysplit voicegroup571, KeySplitTableBW23 @ 17 | Multi | 
	voice_keysplit voicegroup572, KeySplitTableBW24 @ 18 | Multi | 
	voice_keysplit voicegroup573, KeySplitTableBW25 @ 19 | Multi | 
	voice_keysplit voicegroup574, KeySplitTableBW26 @ 20 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample055, 255, 245, 0, 165 @ 21 | Direct | 
	voice_keysplit voicegroup575, KeySplitTableBW27 @ 22 | Multi | 
	voice_keysplit voicegroup576, KeySplitTableBW28 @ 23 | Multi | 
	voice_keysplit voicegroup577, KeySplitTableBW29 @ 24 | Multi | 
	voice_keysplit voicegroup578, KeySplitTableBW30 @ 25 | Multi | 
	voice_keysplit voicegroup579, KeySplitTableBW31 @ 26 | Multi | 
	voice_keysplit voicegroup580, KeySplitTableBW32 @ 27 | Multi | 
	voice_keysplit voicegroup581, KeySplitTableBW33 @ 28 | Multi | 
	voice_keysplit voicegroup582, KeySplitTableBW34 @ 29 | Multi | 
	voice_keysplit voicegroup583, KeySplitTableBW35 @ 30 | Multi | 
	voice_keysplit voicegroup584, KeySplitTableBW36 @ 31 | Multi | 
	voice_keysplit voicegroup585, KeySplitTableBW37 @ 32 | Multi | 
	voice_keysplit voicegroup586, KeySplitTableBW38 @ 33 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample245, 255, 0, 255, 165 @ 34 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample245, 255, 0, 255, 165 @ 35 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample246, 255, 0, 255, 165 @ 36 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample247, 255, 0, 255, 165 @ 37 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample248, 255, 0, 255, 165 @ 38 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample249, 255, 0, 255, 165 @ 39 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample250, 255, 0, 255, 165 @ 40 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample250, 255, 0, 255, 165 @ 41 | Direct | 
	voice_directsound 62, 0, DirectSoundWaveData_BWInstrumentSample250, 255, 0, 255, 165 @ 42 | Direct | 
	voice_directsound 63, 0, DirectSoundWaveData_BWInstrumentSample250, 255, 0, 255, 165 @ 43 | Direct | 
	voice_directsound 64, 0, DirectSoundWaveData_BWInstrumentSample250, 255, 0, 255, 165 @ 44 | Direct | 
	voice_directsound 65, 0, DirectSoundWaveData_BWInstrumentSample250, 255, 0, 255, 165 @ 45 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample251, 255, 0, 255, 165 @ 46 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample252, 255, 0, 255, 165 @ 47 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample252, 255, 0, 255, 165 @ 48 | Direct | 
	voice_directsound 62, 0, DirectSoundWaveData_BWInstrumentSample252, 255, 0, 255, 165 @ 49 | Direct | 
	voice_directsound 63, 0, DirectSoundWaveData_BWInstrumentSample252, 255, 0, 255, 165 @ 50 | Direct | 
	voice_directsound 64, 0, DirectSoundWaveData_BWInstrumentSample252, 255, 0, 255, 165 @ 51 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample253, 255, 0, 255, 165 @ 52 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample253, 255, 0, 255, 165 @ 53 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample253, 255, 0, 255, 165 @ 54 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample253, 255, 0, 255, 165 @ 55 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample154, 255, 245, 90, 165 @ 56 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample155, 255, 245, 90, 165 @ 57 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 58 | Square-1 | --
	voice_keysplit voicegroup578, KeySplitTableBW29 @ 59 | Multi | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 60 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 61 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 62 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 63 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample156, 170, 180, 160, 235 @ 64 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 65 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 66 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 67 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 68 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 69 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 70 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 71 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 72 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 73 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 74 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 75 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 76 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 77 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 78 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 79 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 80 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 81 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 82 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 83 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 84 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 85 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 86 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 87 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 88 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 89 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 90 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 91 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 92 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 93 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 94 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 95 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 96 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 97 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 98 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 99 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 100 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 101 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 102 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 103 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 104 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 105 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 106 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 107 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 108 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 109 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 110 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 111 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 112 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 113 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 114 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 115 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 116 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 117 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 118 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 119 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 120 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 121 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 122 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 123 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 124 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 125 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 126 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 127 | Square-1 | --
