	.align 2
voicegroup544::
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 0 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 1 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 2 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 3 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 4 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 5 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 6 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 7 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 8 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 9 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 10 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 11 | Square-1 | --
	voice_directsound 12, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 12 | Direct | 
	voice_directsound 13, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 13 | Direct | 
	voice_directsound 14, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 14 | Direct | 
	voice_directsound 15, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 15 | Direct | 
	voice_directsound 16, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 16 | Direct | 
	voice_directsound 17, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 17 | Direct | 
	voice_directsound 18, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 18 | Direct | 
	voice_directsound 19, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 19 | Direct | 
	voice_directsound 20, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 20 | Direct | 
	voice_directsound 21, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 21 | Direct | 
	voice_directsound 22, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 22 | Direct | 
	voice_directsound 23, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 23 | Direct | 
	voice_directsound 24, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 24 | Direct | 
	voice_directsound 25, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 25 | Direct | 
	voice_directsound 26, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 26 | Direct | 
	voice_directsound 27, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 27 | Direct | 
	voice_directsound 28, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 28 | Direct | 
	voice_directsound 29, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 29 | Direct | 
	voice_directsound 30, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 30 | Direct | 
	voice_directsound 31, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 31 | Direct | 
	voice_directsound 32, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 32 | Direct | 
	voice_directsound 33, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 33 | Direct | 
	voice_directsound 34, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 34 | Direct | 
	voice_directsound 35, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 35 | Direct | 
	voice_directsound 36, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 36 | Direct | 
	voice_directsound 37, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 37 | Direct | 
	voice_directsound 38, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 38 | Direct | 
	voice_directsound 39, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 39 | Direct | 
	voice_directsound 40, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 40 | Direct | 
	voice_directsound 41, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 41 | Direct | 
	voice_directsound 42, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 42 | Direct | 
	voice_directsound 43, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 43 | Direct | 
	voice_directsound 44, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 44 | Direct | 
	voice_directsound 45, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 45 | Direct | 
	voice_directsound 46, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 46 | Direct | 
	voice_directsound 47, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 47 | Direct | 
	voice_directsound 48, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 48 | Direct | 
	voice_directsound 49, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 49 | Direct | 
	voice_directsound 50, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 50 | Direct | 
	voice_directsound 51, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 51 | Direct | 
	voice_directsound 52, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 52 | Direct | 
	voice_directsound 53, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 53 | Direct | 
	voice_directsound 54, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 54 | Direct | 
	voice_directsound 55, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 55 | Direct | 
	voice_directsound 56, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 56 | Direct | 
	voice_directsound 57, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 57 | Direct | 
	voice_directsound 58, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 58 | Direct | 
	voice_directsound 59, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 59 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 60 | Direct | 
	voice_directsound 61, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 61 | Direct | 
	voice_directsound 62, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 62 | Direct | 
	voice_directsound 63, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 63 | Direct | 
	voice_directsound 64, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 64 | Direct | 
	voice_directsound 65, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 65 | Direct | 
	voice_directsound 66, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 66 | Direct | 
	voice_directsound 67, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 67 | Direct | 
	voice_directsound 68, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 68 | Direct | 
	voice_directsound 69, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 69 | Direct | 
	voice_directsound 70, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 70 | Direct | 
	voice_directsound 71, 0, DirectSoundWaveData_BWInstrumentSample142, 255, 245, 0, 165 @ 71 | Direct | 
	voice_directsound 72, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 72 | Direct | 
	voice_directsound 73, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 73 | Direct | 
	voice_directsound 74, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 74 | Direct | 
	voice_directsound 75, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 75 | Direct | 
	voice_directsound 76, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 76 | Direct | 
	voice_directsound 77, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 77 | Direct | 
	voice_directsound 78, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 78 | Direct | 
	voice_directsound 79, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 79 | Direct | 
	voice_directsound 80, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 80 | Direct | 
	voice_directsound 81, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 81 | Direct | 
	voice_directsound 82, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 82 | Direct | 
	voice_directsound 83, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 83 | Direct | 
	voice_directsound 84, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 84 | Direct | 
	voice_directsound 85, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 85 | Direct | 
	voice_directsound 86, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 86 | Direct | 
	voice_directsound 87, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 87 | Direct | 
	voice_directsound 88, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 88 | Direct | 
	voice_directsound 89, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 89 | Direct | 
	voice_directsound 90, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 90 | Direct | 
	voice_directsound 91, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 91 | Direct | 
	voice_directsound 92, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 92 | Direct | 
	voice_directsound 93, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 93 | Direct | 
	voice_directsound 94, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 94 | Direct | 
	voice_directsound 95, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 95 | Direct | 
	voice_directsound 96, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 96 | Direct | 
	voice_directsound 97, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 97 | Direct | 
	voice_directsound 98, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 98 | Direct | 
	voice_directsound 99, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 99 | Direct | 
	voice_directsound 100, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 100 | Direct | 
	voice_directsound 101, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 101 | Direct | 
	voice_directsound 102, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 102 | Direct | 
	voice_directsound 103, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 103 | Direct | 
	voice_directsound 104, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 104 | Direct | 
	voice_directsound 105, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 105 | Direct | 
	voice_directsound 106, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 106 | Direct | 
	voice_directsound 107, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 107 | Direct | 
	voice_directsound 108, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 108 | Direct | 
	voice_directsound 109, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 109 | Direct | 
	voice_directsound 110, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 110 | Direct | 
	voice_directsound 111, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 111 | Direct | 
	voice_directsound 112, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 112 | Direct | 
	voice_directsound 113, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 113 | Direct | 
	voice_directsound 114, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 114 | Direct | 
	voice_directsound 115, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 115 | Direct | 
	voice_directsound 116, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 116 | Direct | 
	voice_directsound 117, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 117 | Direct | 
	voice_directsound 118, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 118 | Direct | 
	voice_directsound 119, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 119 | Direct | 
	voice_directsound 120, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 120 | Direct | 
	voice_directsound 121, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 121 | Direct | 
	voice_directsound 122, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 122 | Direct | 
	voice_directsound 123, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 123 | Direct | 
	voice_directsound 124, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 124 | Direct | 
	voice_directsound 125, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 125 | Direct | 
	voice_directsound 126, 0, DirectSoundWaveData_BWInstrumentSample143, 255, 245, 0, 165 @ 126 | Direct | 
	voice_directsound 127, 0, DirectSoundWaveData_BWInstrumentSample144, 255, 245, 0, 165 @ 127 | Direct | 
