	.align 2
voicegroup539::
	voice_keysplit voicegroup595, KeySplitTableBW46 @ 0 | Multi | 
	voice_keysplit voicegroup555, KeySplitTableBW07 @ 1 | Multi | 
	voice_keysplit voicegroup556, KeySplitTableBW08 @ 2 | Multi | 
	voice_keysplit voicegroup557, KeySplitTableBW09 @ 3 | Multi | 
	voice_keysplit voicegroup574, KeySplitTableBW26 @ 4 | Multi | 
	voice_keysplit voicegroup555, KeySplitTableBW07 @ 5 | Multi | 
	voice_keysplit voicegroup560, KeySplitTableBW12 @ 6 | Multi | 
	voice_keysplit voicegroup595, KeySplitTableBW46 @ 7 | Multi | 
	voice_keysplit voicegroup562, KeySplitTableBW14 @ 8 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample279, 255, 240, 0, 185 @ 9 | Direct | 
	voice_keysplit voicegroup559, KeySplitTableBW11 @ 10 | Multi | 
	voice_keysplit voicegroup560, KeySplitTableBW12 @ 11 | Multi | 
	voice_keysplit voicegroup566, KeySplitTableBW18 @ 12 | Multi | 
	voice_keysplit voicegroup561, KeySplitTableBW13 @ 13 | Multi | 
	voice_keysplit voicegroup568, KeySplitTableBW20 @ 14 | Multi | 
	voice_keysplit voicegroup569, KeySplitTableBW21 @ 15 | Multi | 
	voice_keysplit voicegroup570, KeySplitTableBW22 @ 16 | Multi | 
	voice_keysplit voicegroup565, KeySplitTableBW17 @ 17 | Multi | 
	voice_keysplit voicegroup553, KeySplitTableBW05 @ 18 | Multi | 
	voice_keysplit voicegroup573, KeySplitTableBW25 @ 19 | Multi | 
	voice_keysplit voicegroup553, KeySplitTableBW05 @ 20 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample055, 255, 245, 0, 165 @ 21 | Direct | 
	voice_keysplit voicegroup575, KeySplitTableBW27 @ 22 | Multi | 
	voice_keysplit voicegroup576, KeySplitTableBW28 @ 23 | Multi | 
	voice_keysplit voicegroup569, KeySplitTableBW21 @ 24 | Multi | 
	voice_keysplit voicegroup573, KeySplitTableBW25 @ 25 | Multi | 
	voice_keysplit voicegroup574, KeySplitTableBW26 @ 26 | Multi | 
	voice_keysplit voicegroup580, KeySplitTableBW32 @ 27 | Multi | 
	voice_keysplit voicegroup600, KeySplitTableBW51 @ 28 | Multi | 
	voice_keysplit voicegroup575, KeySplitTableBW27 @ 29 | Multi | 
	voice_keysplit voicegroup576, KeySplitTableBW56 @ 30 | Multi | 
	voice_keysplit voicegroup584, KeySplitTableBW36 @ 31 | Multi | 
	voice_keysplit voicegroup582, KeySplitTableBW34 @ 32 | Multi | 
	voice_keysplit voicegroup578, KeySplitTableBW30 @ 33 | Multi | 
	voice_keysplit voicegroup579, KeySplitTableBW31 @ 34 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample272, 255, 245, 0, 224 @ 35 | Direct | 
	voice_keysplit voicegroup580, KeySplitTableBW32 @ 36 | Multi | 
	voice_keysplit voicegroup580, KeySplitTableBW32 @ 37 | Multi | 
	voice_keysplit voicegroup581, KeySplitTableBW33 @ 38 | Multi | 
	voice_keysplit voicegroup582, KeySplitTableBW55 @ 39 | Multi | 
	voice_keysplit voicegroup583, KeySplitTableBW35 @ 40 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample145, 255, 245, 130, 165 @ 41 | Direct | 
	voice_keysplit voicegroup596, KeySplitTableBW47 @ 42 | Multi | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 43 | Square-1 | --
	voice_keysplit voicegroup586, KeySplitTableBW38 @ 44 | Multi | 
	voice_keysplit voicegroup587, KeySplitTableBW39 @ 45 | Multi | 
	voice_keysplit voicegroup594, KeySplitTableBW45 @ 46 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample152, 60, 240, 0, 80 @ 47 | Direct | 
	voice_keysplit voicegroup588, KeySplitTableBW40 @ 48 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample195, 255, 245, 0, 165 @ 49 | Direct | 
	voice_keysplit voicegroup598, KeySplitTableBW49 @ 50 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample181, 255, 0, 255, 165 @ 51 | Direct | 
	voice_square_1_alt 60, 0, 0, 2, 0, 5, 4, 1 @ 52 | Square-1 | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 53 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 54 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample153, 255, 245, 90, 185 @ 55 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample154, 255, 245, 90, 185 @ 56 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample155, 255, 245, 90, 185 @ 57 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 58 | Square-1 | --
	voice_keysplit voicegroup578, KeySplitTableBW29 @ 59 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample284, 255, 0, 160, 205 @ 60 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample283, 255, 245, 0, 165 @ 61 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 62 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample358, 255, 0, 255, 165 @ 63 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 64 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 65 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 66 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 67 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 68 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 69 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 70 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 71 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 72 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 73 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample358, 255, 0, 255, 165 @ 74 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample193, 255, 0, 255, 205 @ 75 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 76 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 77 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 78 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 79 | Square-1 | --
	voice_keysplit_all voicegroup543 @ 80 | Drum | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 81 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 82 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 83 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 84 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 85 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample358, 255, 0, 255, 165 @ 86 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 87 | Square-1 | --
	voice_keysplit voicegroup552, KeySplitTableBW04 @ 88 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample345, 255, 250, 0, 165 @ 89 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample285, 255, 250, 0, 165 @ 90 | Direct | 
	voice_keysplit voicegroup551, KeySplitTableBW03 @ 91 | Multi | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample342, 255, 245, 0, 165 @ 92 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample343, 255, 245, 0, 165 @ 93 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 94 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample157, 255, 245, 210, 210 @ 95 | Direct | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 96 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 97 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample182, 255, 0, 225, 165 @ 98 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample166, 255, 0, 225, 165 @ 99 | Direct | 
	voice_keysplit voicegroup578, KeySplitTableBW03 @ 100 | Multi | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 101 | Square-1 | --
	voice_keysplit voicegroup597, KeySplitTableBW48 @ 102 | Multi | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 103 | Square-1 | --
	voice_keysplit voicegroup579, KeySplitTableBW31 @ 104 | Multi | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 105 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 106 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 107 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 108 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 109 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 110 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 111 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 112 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 113 | Square-1 | --
	voice_keysplit_all voicegroup548 @ 114 | Drum | 
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 115 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 116 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 117 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 118 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 119 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 120 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 121 | Square-1 | --
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0 @ 122 | Square-1 | --
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample390, 165, 0, 165, 165 @ 123 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample306, 255, 0, 255, 165 @ 124 | Direct | 
	voice_directsound 60, 0, DirectSoundWaveData_BWInstrumentSample303, 165, 0, 165, 165 @ 125 | Direct | 
	voice_keysplit_all voicegroup547 @ 126 | Drum | 
	voice_keysplit_all voicegroup546 @ 127 | Drum | 
