#ifndef GUARD_CONSTANTS_TMS_HMS_H
#define GUARD_CONSTANTS_TMS_HMS_H

#define FOREACH_TM(F) \
    F(IRON_HEAD) \
    F(DRAGON_CLAW) \
    F(WATER_PULSE) \
    F(CALM_MIND) \
    F(ROAR) \
    F(TOXIC) \
    F(HAIL) \
    F(BULK_UP) \
    F(BULLET_SEED) \
    F(HIDDEN_POWER) \
    F(SUNNY_DAY) \
    F(TAUNT) \
    F(ICE_BEAM) \
    F(BLIZZARD) \
    F(HYPER_BEAM) \
    F(LIGHT_SCREEN) \
    F(PROTECT) \
    F(RAIN_DANCE) \
    F(GIGA_DRAIN) \
    F(WILL_O_WISP) \
    F(FRUSTRATION) \
    F(SOLAR_BEAM) \
    F(IRON_TAIL) \
    F(THUNDERBOLT) \
    F(THUNDER) \
    F(EARTHQUAKE) \
    F(RETURN) \
    F(DIG) \
    F(PSYCHIC) \
    F(SHADOW_BALL) \
    F(BRICK_BREAK) \
    F(FOCUS_BLAST) \
    F(REFLECT) \
    F(ENERGY_BALL) \
    F(FLAMETHROWER) \
    F(SLUDGE_BOMB) \
    F(SANDSTORM) \
    F(FIRE_BLAST) \
    F(ROCK_TOMB) \
    F(AERIAL_ACE) \
    F(AURORA_VEIL) \
    F(FACADE) \
    F(ROOST) \
    F(REST) \
    F(ATTRACT) \
    F(THIEF) \
    F(HONE_CLAWS) \
    F(CHARGE_BEAM) \
    F(COACHING) \
    F(OVERHEAT) \
    F(ACROBATICS) \
    F(TRAILBLAZE) \
    F(BULLDOZE) \
    F(SNARL) \
    F(VENOSHOCK) \
    F(VOLT_SWITCH) \
    F(DRAIN_PUNCH) \
    F(DAZZLING_GLEAM) \
    F(POISON_JAB) \
    F(BODY_PRESS) \
    F(SCALD) \
    F(TAILWIND) \
    F(DRAGON_PULSE) \
    F(ICE_SPINNER) \
    F(SMART_STRIKE) \
    F(STEALTH_ROCK) \
    F(DARK_PULSE) \
    F(LEECH_LIFE) \
    F(TRICK_ROOM) \
    F(BREAKING_SWIPE) \
    F(STONE_EDGE) \
    F(GYRO_BALL) \
    F(SWORDS_DANCE) \
    F(FLAME_CHARGE) \
    F(LOW_SWEEP) \
    F(ROCK_SLIDE) \
    F(X_SCISSOR) \
    F(THUNDER_WAVE) \
    F(U_TURN) \
    F(SUBSTITUTE) \
    F(FLASH_CANNON) \
    F(HEX) \
    F(DRAGON_TAIL) \
    F(ELECTRO_BALL) \
    F(SLUDGE_WAVE) \
    F(ENCORE) \
    F(BRUTAL_SWING) \
    F(PLAY_ROUGH) \
    F(EXPANDING_FORCE) \
    F(SHADOW_CLAW) \
    F(AVALANCHE) \
    F(FOUL_PLAY) \
    F(POWER_GEM) \
    F(CLOSE_COMBAT) \
    F(DRAGON_DANCE) \
    F(PSYSHOCK) \
    F(EARTH_POWER) \
    F(GRASS_KNOT) \
    F(SCALE_SHOT) \

#define FOREACH_HM(F) \
    F(CUT) \
    F(FLY) \
    F(SURF) \
    F(STRENGTH) \
    F(FLASH) \
    F(ROCK_SMASH) \
    F(WATERFALL) \
    F(DIVE)

#define FOREACH_TMHM(F) \
    FOREACH_TM(F) \
    FOREACH_HM(F)

#endif
