gText_Birch_Welcome::
	.string "Hello, allow me to welcome you\n"
	.string "to the online learning portal!\l"
	.string "My name is Professor Pine.\p"
	.string "I will be your instructor for\n"
	.string "today's lesson on Pokémon.\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a Pokémon.\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "The Serenado region is inhabited\n"
	.string "by creatures known as Pokémon.\p"
	.string "However, due to the major geologoical\n"
	.string "shifts in Hoenn a few years ago, the\l"
	.string "Pokémon across Serenado have changed.\p"
	.string "I study the migration of Pokémon in\n"
	.string "response to transforming environments.\p"
	.string "We have seen many Pokémon appear in\n"
	.string "Serenado that we haven't seen before.\p"
	.string "That is why I conduct fieldwork to note\n"
	.string "these new Pokémon, and where they are.\p"
	.string "Even with all of this research, we\n"
	.string "have much to learn about Pokémon.\l"
	.string "My goal is to study them in depth.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "Please input your name to receive\n"
	.string "credit for this lesson.$"

gText_Birch_SoItsPlayer::
	.string "You are {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Thank you for listening!\p"
	.string "You have received credit for today's\n"
	.string "lesson on Pokémon migration.\l"
	.string "I hope you learned a lot!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Now an extra note!\p"
	.string "I will be conducting fieldwork near\n"
	.string "Cairwind Town this week.\p"
	.string "Please feel free to join me in my\n"
	.string "work recording Pokémon, and ask any\l"
	.string "questions you may have for me!\p"
	.string "Log in tomorrow for the next lesson.\n"
	.string "I hope to see you before then!\p"
	.string "$"
